// <auto-generated />
namespace YekanPedia.ManagementSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ignoreielts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ignoreielts));
        
        string IMigrationMetadata.Id
        {
            get { return "201512301407321_ignore ielts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
