// <auto-generated />
namespace YekanPedia.ManagementSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ignore : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ignore));
        
        string IMigrationMetadata.Id
        {
            get { return "201511022151373_ignore"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
