//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YekanPedia.ManagementSystem.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YekanPedia.ManagementSystem.Domain.Properties.DisplayNames", typeof(DisplayNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره من.
        /// </summary>
        public static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تولد.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن تبریک تاریخ تولد.
        /// </summary>
        public static string BirthDateText {
            get {
                return ResourceManager.GetString("BirthDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کتاب.
        /// </summary>
        public static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ظرفیت.
        /// </summary>
        public static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلاسهای فعال.
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلاس.
        /// </summary>
        public static string ClassId {
            get {
                return ResourceManager.GetString("ClassId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات کلاس.
        /// </summary>
        public static string ClassInformaion {
            get {
                return ResourceManager.GetString("ClassInformaion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جلسات برگزار شده.
        /// </summary>
        public static string ClassSession {
            get {
                return ResourceManager.GetString("ClassSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ  برگذاری جلسه.
        /// </summary>
        public static string ClassSessionDateSh {
            get {
                return ResourceManager.GetString("ClassSessionDateSh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان کلاس.
        /// </summary>
        public static string ClassTime {
            get {
                return ResourceManager.GetString("ClassTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع کلاس.
        /// </summary>
        public static string ClassTypeId {
            get {
                return ResourceManager.GetString("ClassTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شرکت.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام موسسه.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ پیوستن به کلاس.
        /// </summary>
        public static string ContributeStartDateSh {
            get {
                return ResourceManager.GetString("ContributeStartDateSh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوره.
        /// </summary>
        public static string CourseId {
            get {
                return ResourceManager.GetString("CourseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوره.
        /// </summary>
        public static string CourseName {
            get {
                return ResourceManager.GetString("CourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ رزومه.
        /// </summary>
        public static string CvColor {
            get {
                return ResourceManager.GetString("CvColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روز.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال اتمام تحصیل.
        /// </summary>
        public static string EducateFinishYear {
            get {
                return ResourceManager.GetString("EducateFinishYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال شروع تحصیل.
        /// </summary>
        public static string EducateStartYear {
            get {
                return ResourceManager.GetString("EducateStartYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پست الکترونیک.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع امتحان.
        /// </summary>
        public static string ExamType {
            get {
                return ResourceManager.GetString("ExamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیسبوک.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رشته تحصیلی.
        /// </summary>
        public static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل ارسالی.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد روز ماندگاری فایل ها.
        /// </summary>
        public static string FilesPersistance {
            get {
                return ResourceManager.GetString("FilesPersistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ اتمام کلاس.
        /// </summary>
        public static string FinishDateSh {
            get {
                return ResourceManager.GetString("FinishDateSh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام و نام خانوادگی.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گوگل پلاس.
        /// </summary>
        public static string GooglePlus {
            get {
                return ResourceManager.GetString("GooglePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فارغ التحصیل.
        /// </summary>
        public static string Graduated {
            get {
                return ResourceManager.GetString("Graduated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کنسلی جلسه.
        /// </summary>
        public static string IsCanceled {
            get {
                return ResourceManager.GetString("IsCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بررسی شده.
        /// </summary>
        public static string IsComplete {
            get {
                return ResourceManager.GetString("IsComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتمام کلاس.
        /// </summary>
        public static string IsFinished {
            get {
                return ResourceManager.GetString("IsFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی برای عموم.
        /// </summary>
        public static string IsPublic {
            get {
                return ResourceManager.GetString("IsPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استاد.
        /// </summary>
        public static string IsTeacher {
            get {
                return ResourceManager.GetString("IsTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ جلسه توجیهی.
        /// </summary>
        public static string JustificationDateSh {
            get {
                return ResourceManager.GetString("JustificationDateSh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان آخرین ورود به سیستم.
        /// </summary>
        public static string LastLoginDate {
            get {
                return ResourceManager.GetString("LastLoginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین زمان بروز رسانی.
        /// </summary>
        public static string LastUpdateDateSh {
            get {
                return ResourceManager.GetString("LastUpdateDateSh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقعیت جغرافیایی.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک دین.
        /// </summary>
        public static string LinkedIn {
            get {
                return ResourceManager.GetString("LinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقعیت جغرافیایی.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال پیام در زمان ارسال فایل های کلاس.
        /// </summary>
        public static string MessageOnAddSession {
            get {
                return ResourceManager.GetString("MessageOnAddSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال پیام تبریک در زمان تاریخ تولد.
        /// </summary>
        public static string MessageOnBirthDate {
            get {
                return ResourceManager.GetString("MessageOnBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال پیام در زمان ثبت کنسلی کلاس.
        /// </summary>
        public static string MessageOnCanceledClass {
            get {
                return ResourceManager.GetString("MessageOnCanceledClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال پیام خصوصی.
        /// </summary>
        public static string MessageOnPrivateMessage {
            get {
                return ResourceManager.GetString("MessageOnPrivateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال پیام در زمان بازیابی کلمه عبور.
        /// </summary>
        public static string MessageOnResetPassword {
            get {
                return ResourceManager.GetString("MessageOnResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال پیام در زمان مناسبت های سالانه.
        /// </summary>
        public static string MessageOnYearEvent {
            get {
                return ResourceManager.GetString("MessageOnYearEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره همراه.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماه.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع ارسال اعلانات.
        /// </summary>
        public static string NotificationType {
            get {
                return ResourceManager.GetString("NotificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ پرداخت هزینه.
        /// </summary>
        public static string PaymentDate {
            get {
                return ResourceManager.GetString("PaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد.
        /// </summary>
        public static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقعیت شغلی.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ ( ریال ).
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت نام.
        /// </summary>
        public static string RegisterDate {
            get {
                return ResourceManager.GetString("RegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ درخواست.
        /// </summary>
        public static string RquestDateSh {
            get {
                return ResourceManager.GetString("RquestDateSh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدرسه / دانشگاه.
        /// </summary>
        public static string School {
            get {
                return ResourceManager.GetString("School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ارسال فایل.
        /// </summary>
        public static string SendDateSh {
            get {
                return ResourceManager.GetString("SendDateSh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد جلسات.
        /// </summary>
        public static string SessionCount {
            get {
                return ResourceManager.GetString("SessionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنسیت.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع کلاس.
        /// </summary>
        public static string StartDateSh {
            get {
                return ResourceManager.GetString("StartDateSh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موضوع.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلگرام.
        /// </summary>
        public static string Telegram {
            get {
                return ResourceManager.GetString("Telegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن .
        /// </summary>
        public static string Telphone {
            get {
                return ResourceManager.GetString("Telphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تست.
        /// </summary>
        public static string TestNumber {
            get {
                return ResourceManager.GetString("TestNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از ساعت.
        /// </summary>
        public static string TimeFrom {
            get {
                return ResourceManager.GetString("TimeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا ساعت.
        /// </summary>
        public static string TimeTo {
            get {
                return ResourceManager.GetString("TimeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موضوع.
        /// </summary>
        public static string Topic {
            get {
                return ResourceManager.GetString("Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد رهگیری بانک.
        /// </summary>
        public static string TransactionCode {
            get {
                return ResourceManager.GetString("TransactionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تویئتر.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع کلاس.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتمام مجوز حضور.
        /// </summary>
        public static string UserInClassIsFinished {
            get {
                return ResourceManager.GetString("UserInClassIsFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشغول به کار.
        /// </summary>
        public static string WorkCurrently {
            get {
                return ResourceManager.GetString("WorkCurrently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال اتمام کار.
        /// </summary>
        public static string WorkFinishYear {
            get {
                return ResourceManager.GetString("WorkFinishYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال شروع به کار.
        /// </summary>
        public static string WorkStartYear {
            get {
                return ResourceManager.GetString("WorkStartYear", resourceCulture);
            }
        }
    }
}
