//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LocalMessage", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره من.
        /// </summary>
        internal static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره ما.
        /// </summary>
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات زیر را با دقت پر نمایید . اطلاعات زیر در تمامیه سیستم ها اعم از تلگرام ، ایمیل ، اس ام اس و غیره مورد استفاده قرار خواهد گرفت.
        /// </summary>
        internal static string AboutUsDescription {
            get {
                return ResourceManager.GetString("AboutUsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال نمودن کاربر.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعالیت ها.
        /// </summary>
        internal static string Activities {
            get {
                return ResourceManager.GetString("Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد نوع کلاس.
        /// </summary>
        internal static string AddClassType {
            get {
                return ResourceManager.GetString("AddClassType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در این قسمت کلیه انواع کلاس های مربوطه مانند خصوصی ، حضوری و غیره را وارد نمایید.
        /// </summary>
        internal static string AddClassTypeDescription {
            get {
                return ResourceManager.GetString("AddClassTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد انواع دوره های آموزشی.
        /// </summary>
        internal static string AddCourse {
            get {
                return ResourceManager.GetString("AddCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در این قسمت کلیه انواع کلاس های مربوطه مانند UniLevel ، PreUniLevel را وارد نمایید.
        /// </summary>
        internal static string AddCourseDescription {
            get {
                return ResourceManager.GetString("AddCourseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافه نمودن تحصیلات.
        /// </summary>
        internal static string AddEducation {
            get {
                return ResourceManager.GetString("AddEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام کاربر در کلاس.
        /// </summary>
        internal static string AddUserInClass {
            get {
                return ResourceManager.GetString("AddUserInClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافه نمودن شغل.
        /// </summary>
        internal static string AddWork {
            get {
                return ResourceManager.GetString("AddWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آواتار.
        /// </summary>
        internal static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات پایه.
        /// </summary>
        internal static string BasicInfo {
            get {
                return ResourceManager.GetString("BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت اطلاعات پایه.
        /// </summary>
        internal static string BasicInfoManagement {
            get {
                return ResourceManager.GetString("BasicInfoManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات تماس.
        /// </summary>
        internal static string CallInfo {
            get {
                return ResourceManager.GetString("CallInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر عکس.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر عکس پروفایل.
        /// </summary>
        internal static string ChangePicture {
            get {
                return ResourceManager.GetString("ChangePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلاس.
        /// </summary>
        internal static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت کلاس ها.
        /// </summary>
        internal static string ClassManagement {
            get {
                return ResourceManager.GetString("ClassManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت زمان های کلاس.
        /// </summary>
        internal static string ClassTimeManagement {
            get {
                return ResourceManager.GetString("ClassTimeManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت به تنظیمات اولیه.
        /// </summary>
        internal static string ClearLocalStorage {
            get {
                return ResourceManager.GetString("ClearLocalStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کامنت ها.
        /// </summary>
        internal static string CommentCount {
            get {
                return ResourceManager.GetString("CommentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بزودی.
        /// </summary>
        internal static string CommingSoon {
            get {
                return ResourceManager.GetString("CommingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات پروفایل شما تکمیل نمی باشد. .
        /// </summary>
        internal static string CompleteProfile {
            get {
                return ResourceManager.GetString("CompleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تماس با ما.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن ....
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوره های گذرانده.
        /// </summary>
        internal static string CourseCompleted {
            get {
                return ResourceManager.GetString("CourseCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوره های جاری.
        /// </summary>
        internal static string CourseCurrents {
            get {
                return ResourceManager.GetString("CourseCurrents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داشبورد.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیر فعال نمودن کاربر.
        /// </summary>
        internal static string DeActive {
            get {
                return ResourceManager.GetString("DeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا با حذف رکورد موافق هستید.
        /// </summary>
        internal static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش آدرس بارگذاری فایل ها.
        /// </summary>
        internal static string DisplayAddress {
            get {
                return ResourceManager.GetString("DisplayAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا اتمام عملیات و ارسال ناتیفیکیشن برای کاربر موافق هستید ؟.
        /// </summary>
        internal static string DoneConfirm {
            get {
                return ResourceManager.GetString("DoneConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتمام رایت فایل درخواستی.
        /// </summary>
        internal static string DoneWrite {
            get {
                return ResourceManager.GetString("DoneWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانلود.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحصیلات.
        /// </summary>
        internal static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس ایمیل.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدون انتخاب.
        /// </summary>
        internal static string EmptySelect {
            get {
                return ResourceManager.GetString("EmptySelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخطار.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج از سیستم.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلاس هایی که تا 2 هفته آینده اتمام خواهند شد.
        /// </summary>
        internal static string ExpiredClass {
            get {
                return ResourceManager.GetString("ExpiredClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانش آموزانی که تا 2 هفته آینده مجوز حضور خواهند شد.
        /// </summary>
        internal static string ExpiredUser {
            get {
                return ResourceManager.GetString("ExpiredUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازخورد.
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد فایل ها.
        /// </summary>
        internal static string FilesCount {
            get {
                return ResourceManager.GetString("FilesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آمار حجمی سرور فایل ها.
        /// </summary>
        internal static string FilesStatistics {
            get {
                return ResourceManager.GetString("FilesStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوستان.
        /// </summary>
        internal static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمام صفحه.
        /// </summary>
        internal static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه اصلی.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین بازدید.
        /// </summary>
        internal static string LastLogin {
            get {
                return ResourceManager.GetString("LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام ها.
        /// </summary>
        internal static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ فایلی آپلود نشده است.
        /// </summary>
        internal static string NoFileUploaded {
            get {
                return ResourceManager.GetString("NoFileUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعلانات.
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آنلاین.
        /// </summary>
        internal static string OnLine {
            get {
                return ResourceManager.GetString("OnLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متوقف کردن زمانیندی.
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هر {0} ثانیه.
        /// </summary>
        internal static string PerSecond {
            get {
                return ResourceManager.GetString("PerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجرا کردن زمانیندی.
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروفایل کاربری.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازیابی کلمه عبور.
        /// </summary>
        internal static string RecoveryPassword {
            get {
                return ResourceManager.GetString("RecoveryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور موقت برای شما ارسال شد. لطفا پس از ورود به سیستم کلمه عبور خود را تغییر نمایید.
        /// </summary>
        internal static string RecoveryPasswordComplete {
            get {
                return ResourceManager.GetString("RecoveryPasswordComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای بازیابی نام کاربری و کلمه عبور خود لطفا آدرس ایمیل خود را وارد نمایید. در صورت تائید آدرس ایمیل نام کاربری و کلمه عبور برای شما ارسال خواهد شد..
        /// </summary>
        internal static string RecoveryPasswordDescription {
            get {
                return ResourceManager.GetString("RecoveryPasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با سپاس فراوان ، ثبت نام شما در سایت یکان پدیا با موفقیت انجام شد.
        /// </summary>
        internal static string RegisterComplete {
            get {
                return ResourceManager.GetString("RegisterComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرا بخاطر بسپار.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت اطلاعات.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت زمانبندی سیستم.
        /// </summary>
        internal static string ScheduleSystem {
            get {
                return ResourceManager.GetString("ScheduleSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب تصویر.
        /// </summary>
        internal static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال پیام.
        /// </summary>
        internal static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام شما به چند طریق پیام کوتاه ، ایمیل ، و تلگرام برای کاربر انتخابی ارسال می گردد.
        /// </summary>
        internal static string SendMessageDescription {
            get {
                return ResourceManager.GetString("SendMessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال ناتیفیکیشن به کاربران.
        /// </summary>
        internal static string SendNotification {
            get {
                return ResourceManager.GetString("SendNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا با ارسال ناتیفیکیشن برای کلاس مربوطه موافق هستید ؟.
        /// </summary>
        internal static string SendNotificationConfirm {
            get {
                return ResourceManager.GetString("SendNotificationConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جلسه.
        /// </summary>
        internal static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت جلسات.
        /// </summary>
        internal static string SessionManagement {
            get {
                return ResourceManager.GetString("SessionManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا فایل های مربوط به جلسه جاری را در مسیر {0} بارگذاری نموده و بر روی بروز رسانی فایل ها کلیک نمایید.
        /// </summary>
        internal static string SessionMaterialAddress {
            get {
                return ResourceManager.GetString("SessionMaterialAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست فایل.
        /// </summary>
        internal static string SessionMaterialRequest {
            get {
                return ResourceManager.GetString("SessionMaterialRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات کاربری.
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مختصری از من.
        /// </summary>
        internal static string ShortAboutMe {
            get {
                return ResourceManager.GetString("ShortAboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به سیستم.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات وب سایت.
        /// </summary>
        internal static string SiteSetting {
            get {
                return ResourceManager.GetString("SiteSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آمار حجمی پنل پیامک.
        /// </summary>
        internal static string SmsStatistics {
            get {
                return ResourceManager.GetString("SmsStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آمار.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد دانش آموزان.
        /// </summary>
        internal static string StudentCount {
            get {
                return ResourceManager.GetString("StudentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بروز رسانی فایل ها.
        /// </summary>
        internal static string SyncMaterial {
            get {
                return ResourceManager.GetString("SyncMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسک های شما.
        /// </summary>
        internal static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدول زمانی.
        /// </summary>
        internal static string TimeLine {
            get {
                return ResourceManager.GetString("TimeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا امروز.
        /// </summary>
        internal static string UptoNow {
            get {
                return ResourceManager.GetString("UptoNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کاربران.
        /// </summary>
        internal static string UserCount {
            get {
                return ResourceManager.GetString("UserCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت کاربران.
        /// </summary>
        internal static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش همه.
        /// </summary>
        internal static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد بازدید سایت.
        /// </summary>
        internal static string WebSiteVisitCount {
            get {
                return ResourceManager.GetString("WebSiteVisitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات شغلی.
        /// </summary>
        internal static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکان پدیا.
        /// </summary>
        internal static string YekanPedia {
            get {
                return ResourceManager.GetString("YekanPedia", resourceCulture);
            }
        }
    }
}
