//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YekanPedia.ManagementSystem.Console.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YekanPedia.ManagementSystem.Console.App_GlobalResources.LocalMessage", typeof(LocalMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره من.
        /// </summary>
        public static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال نمودن کاربر.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعالیت ها.
        /// </summary>
        public static string Activities {
            get {
                return ResourceManager.GetString("Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد نوع کلاس.
        /// </summary>
        public static string AddClassType {
            get {
                return ResourceManager.GetString("AddClassType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در این قسمت کلیه انواع کلاس های مربوطه مانند خصوصی ، حضوری و غیره را وارد نمایید.
        /// </summary>
        public static string AddClassTypeDescription {
            get {
                return ResourceManager.GetString("AddClassTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد انواع دوره های آموزشی.
        /// </summary>
        public static string AddCourse {
            get {
                return ResourceManager.GetString("AddCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در این قسمت کلیه انواع کلاس های مربوطه مانند UniLevel ، PreUniLevel را وارد نمایید.
        /// </summary>
        public static string AddCourseDescription {
            get {
                return ResourceManager.GetString("AddCourseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام کاربر در کلاس.
        /// </summary>
        public static string AddUserInClass {
            get {
                return ResourceManager.GetString("AddUserInClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات پایه.
        /// </summary>
        public static string BasicInfo {
            get {
                return ResourceManager.GetString("BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت اطلاعات پایه.
        /// </summary>
        public static string BasicInfoManagement {
            get {
                return ResourceManager.GetString("BasicInfoManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات تماس.
        /// </summary>
        public static string CallInfo {
            get {
                return ResourceManager.GetString("CallInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر عکس پروفایل.
        /// </summary>
        public static string ChangePicture {
            get {
                return ResourceManager.GetString("ChangePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت کلاس ها.
        /// </summary>
        public static string ClassManagement {
            get {
                return ResourceManager.GetString("ClassManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت زمان های کلاس.
        /// </summary>
        public static string ClassTimeManagement {
            get {
                return ResourceManager.GetString("ClassTimeManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت به تنظیمات اولیه.
        /// </summary>
        public static string ClearLocalStorage {
            get {
                return ResourceManager.GetString("ClearLocalStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات پروفایل شما تکمیل نمی باشد. .
        /// </summary>
        public static string CompleteProfile {
            get {
                return ResourceManager.GetString("CompleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تماس با ما.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن ....
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوره های گذرانده.
        /// </summary>
        public static string CourseCompleted {
            get {
                return ResourceManager.GetString("CourseCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوره های جاری.
        /// </summary>
        public static string CourseCurrents {
            get {
                return ResourceManager.GetString("CourseCurrents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داشبورد.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیر فعال نمودن کاربر.
        /// </summary>
        public static string DeActive {
            get {
                return ResourceManager.GetString("DeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا با حذف رکورد موافق هستید.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانلود.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس ایمیل.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدون انتخاب.
        /// </summary>
        public static string EmptySelect {
            get {
                return ResourceManager.GetString("EmptySelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخطار.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج از سیستم.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازخورد.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمام صفحه.
        /// </summary>
        public static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه اصلی.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام ها.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعلانات.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروفایل کاربری.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازیابی کلمه عبور.
        /// </summary>
        public static string RecoveryPassword {
            get {
                return ResourceManager.GetString("RecoveryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور موقت برای شما ارسال شد. لطفا پس از ورود به سیستم کلمه عبور خود را تغییر نمایید.
        /// </summary>
        public static string RecoveryPasswordComplete {
            get {
                return ResourceManager.GetString("RecoveryPasswordComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای بازیابی نام کاربری و کلمه عبور خود لطفا آدرس ایمیل خود را وارد نمایید. در صورت تائید آدرس ایمیل نام کاربری و کلمه عبور برای شما ارسال خواهد شد..
        /// </summary>
        public static string RecoveryPasswordDescription {
            get {
                return ResourceManager.GetString("RecoveryPasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با سپاس فراوان ، ثبت نام شما در سایت یکان پدیا با موفقیت انجام شد.
        /// </summary>
        public static string RegisterComplete {
            get {
                return ResourceManager.GetString("RegisterComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرا بخاطر بسپار.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت اطلاعات.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال پیام.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مختصری از من.
        /// </summary>
        public static string ShortAboutMe {
            get {
                return ResourceManager.GetString("ShortAboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به سیستم.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسک های شما.
        /// </summary>
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدول زمانی.
        /// </summary>
        public static string TimeLine {
            get {
                return ResourceManager.GetString("TimeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت کاربران.
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش همه.
        /// </summary>
        public static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکان پدیا.
        /// </summary>
        public static string YekanPedia {
            get {
                return ResourceManager.GetString("YekanPedia", resourceCulture);
            }
        }
    }
}
