//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YekanPedia.ManagementSystem.ExternalService.MessagingGateway {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotificationPackage", Namespace="http://schemas.datacontract.org/2004/07/YekanPedia.MessagingGateway.Domain")]
    [System.SerializableAttribute()]
    public partial class NotificationPackage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> SmsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<int> TelegramField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<YekanPedia.ManagementSystem.ExternalService.MessagingGateway.NotificationKey> TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Sms {
            get {
                return this.SmsField;
            }
            set {
                if ((object.ReferenceEquals(this.SmsField, value) != true)) {
                    this.SmsField = value;
                    this.RaisePropertyChanged("Sms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<int> Telegram {
            get {
                return this.TelegramField;
            }
            set {
                if ((object.ReferenceEquals(this.TelegramField, value) != true)) {
                    this.TelegramField = value;
                    this.RaisePropertyChanged("Telegram");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<YekanPedia.ManagementSystem.ExternalService.MessagingGateway.NotificationKey> Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotificationKey", Namespace="http://schemas.datacontract.org/2004/07/YekanPedia.MessagingGateway.Domain")]
    [System.SerializableAttribute()]
    public partial class NotificationKey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SmsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TelegramField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Email {
            get {
                return this.EmailField;
            }
            set {
                if ((this.EmailField.Equals(value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Sms {
            get {
                return this.SmsField;
            }
            set {
                if ((this.SmsField.Equals(value) != true)) {
                    this.SmsField = value;
                    this.RaisePropertyChanged("Sms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Telegram {
            get {
                return this.TelegramField;
            }
            set {
                if ((this.TelegramField.Equals(value) != true)) {
                    this.TelegramField = value;
                    this.RaisePropertyChanged("Telegram");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MessagingGateway.IMessagingGateway")]
    public interface IMessagingGateway {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMessagingGateway/GivenMessages")]
        void GivenMessages(YekanPedia.ManagementSystem.ExternalService.MessagingGateway.NotificationPackage package);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMessagingGateway/GivenMessages")]
        System.Threading.Tasks.Task GivenMessagesAsync(YekanPedia.ManagementSystem.ExternalService.MessagingGateway.NotificationPackage package);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessagingGatewayChannel : YekanPedia.ManagementSystem.ExternalService.MessagingGateway.IMessagingGateway, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessagingGatewayClient : System.ServiceModel.ClientBase<YekanPedia.ManagementSystem.ExternalService.MessagingGateway.IMessagingGateway>, YekanPedia.ManagementSystem.ExternalService.MessagingGateway.IMessagingGateway {
        
        public MessagingGatewayClient() {
        }
        
        public MessagingGatewayClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessagingGatewayClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessagingGatewayClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessagingGatewayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GivenMessages(YekanPedia.ManagementSystem.ExternalService.MessagingGateway.NotificationPackage package) {
            base.Channel.GivenMessages(package);
        }
        
        public System.Threading.Tasks.Task GivenMessagesAsync(YekanPedia.ManagementSystem.ExternalService.MessagingGateway.NotificationPackage package) {
            return base.Channel.GivenMessagesAsync(package);
        }
    }
}
